const question = [
  {
    id: 1,
    question: '1+1=2',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 2,
    question: '2+2=4',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 3,
    question: '3+3=6',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 4,
    question: '4+4=8',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 5,
    question: '5+5=10',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 6,
    question: '6+6=12',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 7,
    question: '7+7=14',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 8,
    question: '8+8=16',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 9,
    question: '9+9=18',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 10,
    question: '10+10=20',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 11,
    question: '1+1=3',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 12,
    question: '2+2=5',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 13,
    question: '3+3=7',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 14,
    question: '4+4=9',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 15,
    question: '5+5=11',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 16,
    question: '6+6=13',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 17,
    question: '7+7=15',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 18,
    question: '8+8=17',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 19,
    question: '9+9=19',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 20,
    question: '10+10=21',
    gametype_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },

  {
    id: 21,
    question: '>',
    gametype_id: 1,
    level: 1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 22,
    question: '<',
    gametype_id: 1,
    level: 1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 23,
    question: '>>',
    gametype_id: 1,
    level: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 24,
    question: '<<',
    gametype_id: 1,
    level: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 25,
    question: '>><',
    gametype_id: 1,
    level: 3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 26,
    question: '<<>',
    gametype_id: 1,
    level: 3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 27,
    question: '>><<',
    gametype_id: 1,
    level: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 28,
    question: '<<>>',
    gametype_id: 1,
    level: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 29,
    question: '>><<>',
    gametype_id: 1,
    level: 5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 30,
    question: '<<>><',
    gametype_id: 1,
    level: 5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 31,
    question: '>><<><',
    gametype_id: 1,
    level: 6,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 32,
    question: '<<>><>',
    gametype_id: 1,
    level: 6,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 33,
    question: '>><<><>',
    gametype_id: 1,
    level: 7,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 34,
    question: '<<>><><',
    gametype_id: 1,
    level: 7,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 35,
    question: '>><<><><',
    gametype_id: 1,
    level: 8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 36,
    question: '<<>><><>',
    gametype_id: 1,
    level: 8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 37,
    question: '>><<><><<',
    gametype_id: 1,
    level: 9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 38,
    question: '<<>><><>>',
    gametype_id: 1,
    level: 9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 39,
    question: '>><<><><<<',
    gametype_id: 1,
    level: 10,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 40,
    question: '<<>><><>>>',
    gametype_id: 1,
    level: 10,
    created_at: new Date(),
    updated_at: new Date(),
  },
]

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('question', question, {})
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('question', {
      id: question.map((collection) => collection.id),
    })
  },
}
