const answer = [
  {
    id: 1,
    question_id: 1,
    answer: 'dung',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 2,
    question_id: 1,
    answer: 'sai',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 3,
    question_id: 2,
    answer: 'dung',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 4,
    question_id: 2,
    answer: 'sai',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 5,
    question_id: 3,
    answer: 'dung',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 6,
    question_id: 3,
    answer: 'sai',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 7,
    question_id: 4,
    answer: 'dung',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 8,
    question_id: 4,
    answer: 'sai',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 9,
    question_id: 5,
    answer: 'dung',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 10,
    question_id: 5,
    answer: 'sai',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 11,
    question_id: 6,
    answer: 'dung',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 12,
    question_id: 6,
    answer: 'sai',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 13,
    question_id: 7,
    answer: 'dung',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 14,
    question_id: 7,
    answer: 'sai',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 15,
    question_id: 8,
    answer: 'dung',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 16,
    question_id: 8,
    answer: 'sai',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 17,
    question_id: 9,
    answer: 'dung',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 18,
    question_id: 9,
    answer: 'sai',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 19,
    question_id: 10,
    answer: 'dung',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 20,
    question_id: 10,
    answer: 'sai',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },

  {
    id: 21,
    question_id: 11,
    answer: 'dung',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 22,
    question_id: 11,
    answer: 'sai',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 23,
    question_id: 12,
    answer: 'dung',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 24,
    question_id: 12,
    answer: 'sai',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 25,
    question_id: 13,
    answer: 'dung',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 26,
    question_id: 13,
    answer: 'sai',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 27,
    question_id: 14,
    answer: 'dung',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 28,
    question_id: 14,
    answer: 'sai',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 29,
    question_id: 15,
    answer: 'dung',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 30,
    question_id: 15,
    answer: 'sai',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 31,
    question_id: 16,
    answer: 'dung',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 32,
    question_id: 16,
    answer: 'sai',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 33,
    question_id: 17,
    answer: 'dung',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 34,
    question_id: 17,
    answer: 'sai',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 35,
    question_id: 18,
    answer: 'dung',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 36,
    question_id: 18,
    answer: 'sai',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 37,
    question_id: 19,
    answer: 'dung',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 38,
    question_id: 19,
    answer: 'sai',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 39,
    question_id: 20,
    answer: 'dung',
    correct_answer: false,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 40,
    question_id: 20,
    answer: 'sai',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },

  {
    id: 41,
    question_id: 21,
    answer: '>',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 42,
    question_id: 22,
    answer: '<',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 43,
    question_id: 23,
    answer: '>>',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 44,
    question_id: 24,
    answer: '<<',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 45,
    question_id: 25,
    answer: '>><',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 46,
    question_id: 26,
    answer: '<<>',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 47,
    question_id: 27,
    answer: '>><<',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 48,
    question_id: 28,
    answer: '<<>>',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 49,
    question_id: 29,
    answer: '>><<>',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 50,
    question_id: 30,
    answer: '<<>><',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 51,
    question_id: 31,
    answer: '>><<><',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 52,
    question_id: 32,
    answer: '<<>><>',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 53,
    question_id: 33,
    answer: '>><<><>',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 54,
    question_id: 34,
    answer: '<<>><><',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 55,
    question_id: 35,
    answer: '>><<><><',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 56,
    question_id: 36,
    answer: '<<>><><>',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 57,
    question_id: 37,
    answer: '>><<><><<',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 58,
    question_id: 38,
    answer: '<<>><><>>',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 59,
    question_id: 39,
    answer: '>><<><><<<',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 60,
    question_id: 40,
    answer: '<<>><><>>>',
    correct_answer: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
]

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('answer', answer, {})
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('answer', {
      id: answer.map((collection) => collection.id),
    })
  },
}
